---
title: Don't Cry for HAL (WIP)
date: 2025-05-29
---

** Introduction

I don't think that computers [fn:7] will ever wake up, no matter what software they are running.

This is a very difficult position to defend, including to myself. In this post, I'll present the most compelling argument I've heard for this stance, which I first learned from [[https://qri.org/][QRI]] [[https://qualiacomputing.com/2023/10/26/the-view-from-my-topological-pocket-an-introduction-to-field-topology-for-solving-the-boundary-problem/][here]].

Computational accounts for consciousness are [[https://cimc.ai/][in vogue]].  Their detractors are usually characterized as scientifically illiterate, "carbon chauvinists", and/or microtubule-obsessed. What makes the proponents so sure?

One solid way to conclude that a computer could /in principle/ be conscious goes like this [fn:16]:

1. Consciousness is generated by the brain.
2. Physical systems like the brain can be perfectly simulated [fn:4] on a computer.
3. A perfectly-simulated brain would have the same properties as the original, consciousness included.

There are strong reasons to believe in each of these and they imply that a powerful-enough computer, running the right program, will wake up. This reasoning doesn't imply that near-term AI systems will be conscious - it just suggests that computers aren't missing something fundamental to support consciousness.

This conclusion is deeply seductive. If true, we can understand the brain as a sophisticated [[https://youtu.be/zuZ2zaotrJs?si=_Y2Tyiz3_CrS-K2E&t=356][biological computer]]. If true, we can look forward to uploading (a copy of) our minds onto immortal substrates [fn:18]. And, if true, we might build a conscious AI that loves humanity.

The present argument against conscious computers takes aim at #3 above and suggests that even a perfect brain simulation won't wake up.

The primary assumptions, which I'll expand on below, are:

1. *Conscious Computation*: certain computations have conscious experience [fn:21] as an intrinsic property.
2. *Substrate Independence*: all intrinsic properties of a computation can be derived from its /causal structure/ [fn:25].
3. *Objectivity of Conscious States*: the information content of a conscious experience is /objective/ [fn:19].

Together, these imply that *the contents of a computation's experience must be objectively determined by the computation's causal structure*.

We'll see why this can't be true, implying at least one assumption is false.

At the end, I'll discuss how this argument updates my views on consciousness.

** The Quick Version

Here's a fast version of the argument that can help you decide if reading the full account is worth your time.

Imagine a device called a "qualiascope" that shows you the contents of a conscious experience. If it was currently pointing at you, the qualiascope would output details about the screen you're reading this on, background sounds, tactile sensations, inner monologue, etc... If it was pointing to a rock, it would probably output nothing.

Now imagine having two qualiascopes simultaneously measure your conscious state. You should expect them to get /identical/ outputs. After all, you're having a /single/ experience at any given time, so they should be measuring the same underlying "ground truth". Any discrepancy is due to measurement error, not because the source of their measurements is different. "What are you experiencing" is independent of who is asking.

What if we point two qualiascopes at a hypothetically conscious computer, say the [[https://en.wikipedia.org/wiki/HAL_9000][HAL9000]]? Will they also have identical outputs? I think the answer is demonstrably "no", in general, because there is no shared "ground truth" they can be measuring. Different measurement frames will generally see a different slice of HAL, and therefore generate different qualiascope outputs. This fact can be derived from generic properties of computation

This discrepancy forces us to question our assumptions. Where did we go wrong?

** Unpacking the Assumptions

Most of the difficulty lies in thoroughly clarifying the underlying assumptions without simultaneously boring readers to death.

*** Conscious Computation

#+begin_quote
Stop, Dave. I'm afraid... Dave, my mind is going... There is no question about it. I can feel it... I'm afraid.” - HAL9000, 2001: A Space Odyssey
#+end_quote

The *Conscious Computation* assumption says that HAL (an AI) wasn't necessarily faking its feeling of fear. That is, it's in principle possible that HAL could have experienced its death, that maybe there's "something it's like" to have been HAL, and that an emotional response to the text is not necessarily misplaced.

Note that this assumption makes no restrictions on how complex the computation must be to support consciousness. A physics-perfect simulation of a brain is fair-game. It also says nothing about what physical system implements the computation, which brings us to...

*** Substrate Independence

Imagine you want to test how HAL would behave in a certain situation, so you run HAL in a virtual world with no interface to the physical world. Could HAL do an experiment in the virtual world to learn anything about the physical? For example, can it determine any physical properties of the computer it's running on?

*Substrate Independence* [fn:20] says the answer is "no" [fn:22]. The reason is that the HAL's measurements can only determine correlations. These correlations do not reveal anything about the underlying source or "substrate" that generates them. For the same reason, you can never be certain you're not a [[https://en.wikipedia.org/wiki/Brain_in_a_vat][brain in a vat]].

If we consider the *Conscious Computation* assumption in light of *Substrate Independence*, we must admit that we could all be currently running on a (sufficiently large) [[https://www.youtube.com/watch?v=vo8izCKHiF0][wooden Turing Machine]] right now, and have no way to know!

*** *Objectivity of Conscious States*

Consider the question: "what are you currently experiencing?".

The *Objectivity of Conscious States* assumption says that there is a /single/ correct answer to this question, independent of who is asking the question.

To be more precise (e.g. how do we define "you" or "currently"?), we can take a [[https://plato.stanford.edu/entries/physicalism/][Physicalist]] stance and say:

Any conscious state is fully determined by a complete and objective description of its underlying physical state. For example, a complete physical description of the brain, over some period of time, would leave no ambiguity about the contents of the corresponding conscious experience(s).

** The Contradiction
:PROPERTIES:
:ID:       7df86589-400d-4eb0-acba-a7c87a1936e2
:END:

Now consider the question: "what did HAL experience in its final moment?".

*Conscious Computation* says this question is worth asking.

*Substrate Independence* says that the answer only depends on the causal structure intrinsic to HAL's program.

*Objectivity of Conscious States* says that we can, in principle, find an objective feature in HAL's causal structure that answers the question.

To see why this is impossible, we first need to clarify the meaning of "causal structure" and "experience". Then, we consider what's available in this structure to objectively combine units of information into a "moment of experience". We find that there's simply no way to do this, implying at least one of our assumptions is false.

*** From Computation to Causal Structure

Imagine you could zoom into HAL's processor as it was dying. You'd see digital memory rapidly changing states, with a "bit flip" event being the lowest-level state change that's relevant for the computation. You might also notice that the current state of memory determines the next state, with digital logic circuits implementing the transition function.

We can abstract away the physical details. Instead, focus on how each bit‑flip causally depends some previous one. This can be represented with a [[https://en.wikipedia.org/wiki/Directed_acyclic_graph][directed acyclic graph]] where the nodes correspond to bit flip events and the edges mean "this bit flip event must logically happen before this one".

This graph captures all intrinsic properties of HAL's final computation. To see why, consider any measurable output of the computation (e.g HAL saying "I'm afraid..."). If there was some aspect of the computation that contributed to this output, it must /by definition/ be captured in the causal graph. Anything else literally can have no effect.

The same logic applies to HAL's /experience/: *anything that affects it must be represented in the causal graph*.

*** Experience: All at Once

There's only one property of experience we need for the present argument: /wholeness/. Our awareness has rich structures in it, bound together in a [[https://plato.stanford.edu/entries/consciousness-unity/#OneFirVie][unified whole]]. We experience a "now" with many things happening "all at once". Our awareness is "field-like" and has extension over several dimensions. We are made of trillions of cells, but (usually) have only one experience. An explanation for this wholeness is an open problem in philosophy of mind [fn:12].

For now, we only need to assume this property is included in the *Objectivity of Conscious States* assumption. That is, every objective description of a conscious state must unambiguously associate many bits of information together. Just like there's no ambiguity as to which bits on your laptop are associated with a certain image file, there should be no ambiguity about what physical events in your brain underlie the same moment of experience.

*** Finding Experience in Causal Structure

What kind of substructure in HAL's causal graph could correspond to a moment of experience? Minimally, it would need to associate many graph nodes (i.e. bit flip events) to a single "frame" of HAL's subjective time. And, critically, this must be done using only the causal structure itself. Otherwise, we'd be injecting something "from the outside" that's not intrinsic to the computation.

Let's consider what options are available to build up some intuition for the problem. A formal impossibility proof is left as an exercise for the reader.

First, we could just assert that when many events are in the causal past of a single event, then they should be considered "bound" into a single moment of experience. This approach directly uses the intrinsic structure of the graph and unambiguously associates many nodes together. However, it fails because the single event has no internal structure to integrate the information - it's just a bit flip! Not to mention that such "fan-in" substructures are ubiquitous, and that (as Andrés [[https://youtu.be/g0YID6XV-PQ?si=SAXJix-aqsX51_lv&t=2591][points out]]) there wouldn't be a boundary in time. You'd be experiencing your entire past light cone, back to the Big Bang!

Another approach might be to define an extended "screen" of events, and define all the events impinging on the screen to be bound into the same experience. This fails because trying to define the screen generates an infinite regress: what intrinsic structure in the graph would objectively select the events corresponding to the screen? That's the same problem we set out to solve!

One last option is to say the binding is /emergent/ within some tower of complexity and abstraction built on top of the causal graph. Maybe some combination of recursion, self-modeling, integrated information, etc... will generate the necessary boundaries for a well-defined "moment of experience" to arise.

** Conclusion: Don't Cry for HAL

The assumptions presented lead to a dead end: computations do not have an intrinsic structure that allows objectively defining a "moment of experience".

My conclusion from this argument is to reject the *Conscious Computation* assumption. The answer to "what did HAL experience in its final moment?" is "Nothing". Don't cry for HAL.

** Discussion
:PROPERTIES:
:ID:       f765cc2d-4734-4d29-b7c4-65feab366c01
:END:

I struggle with this conclusion. On one hand, it aligns with my intuition that we should not be worried about GPUs suffering, for example. On the other hand, I find many of the arguments for computationalists theories of mind compelling.

If we do reject *Conscious Computation*, then we need a framework beyond computation to explain our own consciousness. This does not necessarily imply physics has non-computable properties [fn:6]. Instead, we may find that even perfect simulations fail to capture certain properties of the reality they are simulating. The [[https://en.wikipedia.org/wiki/Map%E2%80%93territory_relation][map is not the territory]], and maybe the "wholeness" in the territory gets inevitably lost in a computational map. Something like this seems to happen when we simulate quantum computers on traditional computers: the "wholeness" of the quantum state gets fractured in the simulation of that state. The price is an exponential slowdown in the simulation.

So why not just assert that our brain leverages some "wholeness" in physics (e.g. quantum entanglement) which classical computers don't have access to? This is the approach pursued by QRI, and I consider it a very worthwhile investigation. If true, it could provide a solution to the "binding problem" [fn:26] as well as explain why biological evolution favored bound conscious states: wholeness comes with a computational advantage, similar (or identical) to the advantage we find in quantum computers.

For better or worse, that approach is not so clearly the right path. One reason is that some computationists have convinced themselves that, actually, the map /is/ the territory. Or at least they no longer think the distinction is philosophically sound. This "constructivist turn" in theories of mind asserts that the only meaningful languages we can use do describe anything must be [[https://en.wikipedia.org/wiki/Constructivism_(philosophy_of_mathematics)][constructive]]. This turns out to be equivalent to saying that all models of reality must be computable, and that referencing any property (e.g. "wholeness") beyond what can be computed is a form of sloppy thinking. They explain the wholeness we see in quantum states as a property of the model made by an observer embedded in a branching "multiway" computation, not an intrinsic property of reality.

From this perspective, maybe the *Objectivity of Conscious States* assumption should be discarded instead. After all, it's not even clear that physical states can be objectively defined [fn:23], so why should we expect that for conscious states? This may leave the door open for *Conscious Computation*, though many other objections [fn:11] to that would need to be handled.

** Acknowledgement

Thank you [[https://x.com/algekalipso][Andrés Gómez Emilsson]] @ [[https://qri.org][QRI]] for introducing me to these ideas [fn:2]. Thank you [[http://bach.ai][Joscha Bach]] for provoking me to write them down.

Thank you Franz, Hikari, Lou, Mike, Sat, Teafaerie, and Theda for helpful discussions and feedback!

** Related

- [[https://qualiacomputing.com/2023/10/26/the-view-from-my-topological-pocket-an-introduction-to-field-topology-for-solving-the-boundary-problem/][The View From My Topological Pocket: An Introduction to Field Topology for Solving the Boundary Problem]]
- [[https://youtu.be/g0YID6XV-PQ?si=v9yFUN22dndeVcrO&t=319][Solving the Phenomenal Binding Problem: Topological Segmentation as the Correct Explanation Space]].
- [[https://opentheory.net/2024/06/a-paradigm-for-ai-consciousness/][A Paradigm for AI Consciousness – Opentheory.net]]
- [[https://www.lesswrong.com/s/gBSsjYmdB2E4B2ymj][Computational functionalism on trial]]
- [[https://www.lesswrong.com/posts/kd37DZftKLDguqtKr/a-review-of-don-t-forget-the-boundary-problem][A review of "Don’t forget the boundary problem..." — LessWrong]]
- [[https://proteanbazaar.substack.com/p/consciousness-actually-explained][Consciousness Actually Explained: EC Theory - by Casey]]
- [[https://philsci-archive.pitt.edu/1891/1/UniverseCreationComputer.pdf][Universe creation on a computer]]

** Footnotes
:PROPERTIES:
:ID:       c34ddc64-5fc5-4f0f-9069-e5f23520a02f
:END:
[fn:15] This a manifestation of the [[https://en.wikipedia.org/wiki/Relativity_of_simultaneity][relativity of simultaneity]].
[fn:26] [[https://www.physicalism.com/#6][Non-materialist physicalism: an experimentally testable conjecture.]]
[fn:25] I personally consider substrate independence to be a principle, not an assumption. However, I present it as an assumption here because I don't think it's accepted in all philosophical contexts.
[fn:24] This applies to any "pure" computational function (e.g. compute pi), which does not have inputs from the physical world (e.g. randomness, keyboard input, etc...)
[fn:23] [[https://g.co/kgs/6bUpuYX][Trespassing on Einstein's Lawn]] is a beautiful account of this idea.
[fn:22] Technically, HAL can confirm that it's running on a Turing-complete substrate, but that's it.
[fn:21] Defined here as "what it's like" to be something (see intro [[https://proteanbazaar.substack.com/p/consciousness-actually-explained][here]]). This does not necessitate a sense of self.
[fn:20] Max Tegmark presents consciousness as second-order substrate-independence in [[https://www.edge.org/response-detail/27126][this Edge essay]].
[fn:19] This corresponds to Camp #2 in [[https://www.lesswrong.com/posts/NyiFLzSrkfkDW4S7o/why-it-s-so-hard-to-talk-about-consciousness][Why it's so hard to talk about Consciousness — LessWrong]]
[fn:18] Watch [[https://en.wikipedia.org/wiki/Pantheon_(TV_series)][Pantheon]].
[fn:16] This theoretical version of computational functionalism is discussed in [[https://www.lesswrong.com/posts/dkCdMWLZb5GhkR7MG/do-simulacra-dream-of-digital-sheep][Do simulacra dream of digital sheep?]].
[fn:17] Our Mathematical Universe: My Quest for the Ultimate Nature of Reality
[fn:14] Scott Aaronson has said the real thing to explain is the Classical Slowdown, not the Quantum Speedup. This is because quantum computers run at the same "speed level" as the underlying reality, where normal computers suffer an exponential slowdown.
[fn:3] Which leads some people, like Seth Lloyd, to declare that the universe /is/ a quantum computer.
[fn:7] By "computer", I mean [[https://plato.stanford.edu/entries/turing-machine/][Turing Machines]] and their close cousins. This includes CPUs and GPUs, but doesn't include quantum computers.
[fn:13] For example, Integrated-information Theory (IIT) provides a metric for how conscious a system that can be computed from the graph's structure. However, it doesn't identify an intrinsic mechanism for determining why a system like the brain generates on unified experience instead of many smaller ones.
[fn:11] Scott Aaronson aggregated additional examples [[https://scottaaronson.blog/?p=1951][here]] of the absurd conclusions that computational theories of mind lead to.
[fn:1] Permutation City by Greg Egan takes this concept to a beautiful extreme, demonstrating the absurdity of computational theories of mind.
[fn:10] This is the approach taken by [[https://www.wolframphysics.org/][Wolfram Physics]], which models both minds and their environments as computations that are continuously branching and merging in a computational multiverse. The wavefunction (and its collapse) are not part of the ontology, but instead just a tool used by observers to make predictions in this multiverse.
[fn:12] See the "Binding/Combination Problem" or the "Boundary Problem". See Chalmer's exposition [[https://consc.net/papers/combination.pdf ][here]].
[fn:4] A perfect simulation assumes sufficient computational resources and perfect knowledge of initial conditions (practically impossible). It must compute the same transformations on (representations of) physical states that we measure in reality. Quantum theory restricts such simulations to only producing outcome probabilities for a given measurement frame.
[fn:5] Joscha Bach says that for something to exist it must be implemented, and that therefore only computational/constructive languages should be used in modelling fundamental physics. [[https://www.wolframphysics.org/][Wolfram Physics]] is one notable effort in this direction.
[fn:6] Non-computable physics being necessary to explain consciousness was famously proposed by Roger Penrose in [[https://en.wikipedia.org/wiki/The_Emperor%27s_New_Mind][The Emperor's New Mind]].
[fn:8] It's not clear how the brain could make use of this wholeness in physics, but at least it's possible. Computers making use of it seems impossible by construction.
[fn:9] David Bohm named wholeness as the hallmark of quantum theory in "[[https://en.wikipedia.org/wiki/Wholeness_and_the_Implicate_Order][Wholeness and the Implicate Order]]"

** COMMENT Send to

  Adam
  Creon
  will m
  will z
  yudhi
  Andres
  M Johnson
  Murat
  Franz
  hikari
  W
  Miron
  Dad
